name: blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}         
          username: ${{ secrets.USER }}     
          key: ${{ secrets.PRIVATE_KEY }} 
          source: "public/"
          target: "site/newBranch"
          strip_components: 0

      - name: Finalize Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            rm -rf site/mainBranch
            mv site/newBranch site/mainBranch
            mkdir site/newBranch

            if ! docker ps --filter "name=student004" --format '{{.Names}}' | grep -q '^student004$'; then
              echo "Container is not running. Starting it now..."
              docker start student004
            else
              echo "Container is already running."
            fi